title: Emma the Eng
email: emmatheeng@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Emma, a software engineer working in London.
  I blog about everything, from personal coding projects,
  working in tech and female empowerment. Nice to meet you :-)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: emmatheeng
google_analytics: G-YRZS6C454V
show_excerpts: true
permalink: /:categories/:title:output_ext

header_pages:
  - projects/index.html
  - about.markdown

# Build settings
theme: minima
plugins:
  - jekyll-feed
